#!/usr/bin/env bash
# because orangepi os uses china mirrors and that is too slow for building on github
########

# Source error handling, leave this in place
set -xe

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

echo "deb http://deb.debian.org/debian bullseye main contrib non-free
deb http://deb.debian.org/debian bullseye-updates main contrib non-free

deb http://deb.debian.org/debian bullseye-backports main contrib non-free
#deb http://deb.debian.org/debian bullseye-security main contrib non-free" > /etc/apt/sources.list